/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import entity.Diary;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rifqi
 */
public class MainUI extends javax.swing.JFrame {

   Diary diary;
     public MainUI() {
        initComponents();
        setLocationRelativeTo(null);
     
       
        tampilDiary("");
        TAisi.setLineWrap(true);
        TAisi.setWrapStyleWord(true);
        TFid.setVisible(false);

        
    }

    
     //membuat array list pertama yaitu diaryku
    public static ArrayList<Diary> diaryku = new ArrayList<Diary>();
//    public void tesTanpaBtTambah(){
//        diaryku.add(new Diary(1,"25 November 2003","Kerja","hahahah"));
//        diaryku.add(new Diary(2,"03 Januari 2004","Liburan","wwkwkwk"));
//    }
    
    //query data
    public void getDataDiary(String key){
        //array list yang dipakai jika sedang mencari
       ArrayList<Diary> listdiary = new ArrayList<Diary>();
       //jika key tidak sama dengan kosong didalam arraylist diaryku tambahkan kedalam listdiary yang mana key sama dengan isi diaryku 
       if(!key.equals("")){
           for(Diary x:diaryku){
               if(x.getSubject().toLowerCase().contains(key.toLowerCase()) || x.getDate().toLowerCase().contains(key.toLowerCase())){
                   listdiary.add(x);
           } 
       }
         //jika tidak samakan isi listdiary dengan diaryku
       }else{
               listdiary = diaryku;
               }
       //membuat objek baru tabel model untuk mengakses tbdiary
        DefaultTableModel dri = (DefaultTableModel)TBdiary.getModel();
        //untuk mmebuat baris dan  4 kolom data 
        Object [] row = new Object[4];
        
        //ini perulangan untuk mendapatkan data dari object listdiary berdasarkan size nya
        for(int i =0; i< listdiary.size(); i++){
            //i = baris dan kolom sudah ditentukan dibawah 0-3 (4) kolom
            row[0] = listdiary.get(i).getId();
            row[1] = listdiary.get(i).getDate();
            row[2] = listdiary.get(i).getSubject();
            row[3] = listdiary.get(i).getIsi();
            
            //membuat baris baru di object dri berdasarkan data dari object row
            dri.addRow(row);
        }
    }
      //refresh method
    public final void tampilDiary(String key){
        DefaultTableModel dri = (DefaultTableModel)TBdiary.getModel();
        //setting baris ke 0
        dri.setRowCount(0);
        //lakukan query
        getDataDiary(key);
    }
    //method yang digunakan untuk megakses tanggal di tabel dan membalikkannya menjadi format tanggal
     public Date getDate2(String date){
         SimpleDateFormat tglf = new SimpleDateFormat("dd MMMM yy");
        try{
            Date tgledit = (Date) tglf.parse(date);
            return tgledit;
        }catch (ParseException ex){
            System.err.println("Error Tanggal : "+ex);
            return new Date(System.currentTimeMillis());
        }
    }
     //membuat id otomatis
     public int uniqueId(){
         //megambil index terakhir pada diaryku
         Diary row = diaryku.get(diaryku.size()-1);
         //setelah ketemu maka tambahkan satu  agar tidak menabrak data sebelumya
         int id = row.getId()+1;
         return id;
     }
     //reset field
     public void reset(){
         TFsubject.setText("");
         TAisi.setText("");
         TFcari.setText("");
         TFid.setText("");
         
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TFsubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAisi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        TFid = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        BTsimpan = new javax.swing.JButton();
        BTedit = new javax.swing.JButton();
        BThapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BTimpor = new javax.swing.JButton();
        BTexit = new javax.swing.JButton();
        BTreset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBdiary = new javax.swing.JTable();
        BTtabel = new javax.swing.JButton();
        TFcari = new javax.swing.JTextField();
        BTcari = new javax.swing.JButton();
        BTDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        TAisi.setColumns(20);
        TAisi.setRows(5);
        jScrollPane1.setViewportView(TAisi);

        jLabel1.setText("Tanggal  :");

        jLabel2.setText("Subject :");

        jLabel3.setText("Isi :");

        jDateChooser1.setDateFormatString("dd MMMM yyyy");

        jCheckBox1.setText("Ambil Tanggal Hari ini");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 554, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TFsubject, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opsi"));

        BTsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-check-25.png"))); // NOI18N
        BTsimpan.setText("Simpan");
        BTsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsimpanActionPerformed(evt);
            }
        });

        BTedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-25.png"))); // NOI18N
        BTedit.setText("Edit");
        BTedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTeditActionPerformed(evt);
            }
        });

        BThapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-25.png"))); // NOI18N
        BThapus.setText("Hapus");
        BThapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThapusActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Grey White Vintage Scrapbook My Diary Journal Cover A4 Document (1).png"))); // NOI18N

        BTimpor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-import-30.png"))); // NOI18N
        BTimpor.setText("Import");
        BTimpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTimporActionPerformed(evt);
            }
        });

        BTexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-25.png"))); // NOI18N
        BTexit.setText("Keluar");
        BTexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTexitActionPerformed(evt);
            }
        });

        BTreset.setText("Reset");
        BTreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTexit)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BThapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(BTedit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTimpor)))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTsimpan)
                    .addComponent(BTedit)
                    .addComponent(BTimpor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTreset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BThapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTexit)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("List Diary"));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseReleased(evt);
            }
        });

        TBdiary.setBackground(new java.awt.Color(255, 255, 153));
        TBdiary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Tanggal", "Subject", "Isi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBdiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBdiaryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBdiary);
        if (TBdiary.getColumnModel().getColumnCount() > 0) {
            TBdiary.getColumnModel().getColumn(0).setMinWidth(0);
            TBdiary.getColumnModel().getColumn(0).setPreferredWidth(0);
            TBdiary.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        BTtabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-print-25.png"))); // NOI18N
        BTtabel.setText("Cetak Tabel");
        BTtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BTtabelMouseReleased(evt);
            }
        });
        BTtabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTtabelActionPerformed(evt);
            }
        });

        TFcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFcariActionPerformed(evt);
            }
        });
        TFcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFcariKeyTyped(evt);
            }
        });

        BTcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-15.png"))); // NOI18N
        BTcari.setText("Cari");
        BTcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcariActionPerformed(evt);
            }
        });

        BTDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-detail-15.png"))); // NOI18N
        BTDetail.setText("Detail");
        BTDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTtabel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TFcari, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTcari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTtabel)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BTDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTcari))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//refresh
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampilDiary("");
    }//GEN-LAST:event_formWindowActivated
//method simpan
    private void BTsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsimpanActionPerformed
   //validasi jika tabel kosong
        int id = 0;
      if(diaryku.isEmpty()){
          id = 1;
      }else{
          id = uniqueId();
      }
      //input -input
        SimpleDateFormat tglf = new SimpleDateFormat("dd MMMM yyyy") ;
        String date = tglf.format(jDateChooser1.getDate());
        String subject = TFsubject.getText();
        String isi = TAisi.getText();
        //perintah input
        diaryku.add(new Diary(id,date,subject,isi));
        tampilDiary("");
        reset();
    }//GEN-LAST:event_BTsimpanActionPerformed
//method edit
    private void BTeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTeditActionPerformed
        //validasi jika tabel belum diklik
        if (TFid.getText().equals("")){
            JOptionPane.showMessageDialog(
                    null,
                    ", Silahkan Klik dulu tablenya", "Pesan Kesalahan",
                    JOptionPane.ERROR_MESSAGE
            );
        }else{
            //mengambil data dari tbdiary menggunakan objek data
         TableModel data = TBdiary.getModel();
        int row = TBdiary.getSelectedRow(); 
        //konfirmasi untuk mengedit
        int result= JOptionPane.showConfirmDialog(this,"Apakah Anda Yakin Ingin mengubah data "+ data.getValueAt(row, 1).toString(),"Edit",
                JOptionPane.YES_NO_OPTION);
        if (result==0)
        {
        SimpleDateFormat tglf = new SimpleDateFormat("dd MMMM yyyy");
        String date = tglf.format(jDateChooser1.getDate());
        String subject = TFsubject.getText();
        String isi = TAisi.getText();
        
        
        int index = 0;
        //melakukan perulangan dengan variabel p yang isinya dari diaryku
        for(Diary p: diaryku){
            //pengeceka jika ada didalam diaryku ada id yang saman dengan tfid
            if(p.getId() == Integer.parseInt(TFid.getText())){
                index = diaryku.indexOf(p);
                        break;
            }
        }
        //mengset arraylist diaryku pada index yang sudah didapatkan
        diaryku.set(index,new Diary(Integer.parseInt(TFid.getText()),date,subject,isi));
        tampilDiary("");
        reset();
        }
        }
        
    }//GEN-LAST:event_BTeditActionPerformed
//unutk mengembalikan data masing masing jika tabel diklik
    private void TBdiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBdiaryMouseClicked
        TableModel data = TBdiary.getModel();
        int row = TBdiary.getSelectedRow();
        //mengambil data dengan ketenutan object data sebagai tabel dan var row sebagai baris nya dan disesuaikan urutan colomn yaitu 4
        TFid.setText(data.getValueAt(row, 0).toString());
        jDateChooser1.setDate(getDate2(data.getValueAt(row, 1).toString()));
        TFsubject.setText(data.getValueAt(row, 2).toString());
        TAisi.setText(data.getValueAt(row, 3).toString());
    }//GEN-LAST:event_TBdiaryMouseClicked
//method hapus
    private void BThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThapusActionPerformed
        //validasi hapus
        if (TFid.getText().equals("")){
            JOptionPane.showMessageDialog(
                    null,
                    ", Silahkan Klik dulu tablenya", "Pesan Kesalahan",
                    JOptionPane.ERROR_MESSAGE
            );
        }else{
        TableModel data = TBdiary.getModel();
        int row = TBdiary.getSelectedRow(); 
        int result= JOptionPane.showConfirmDialog(this,"Apakah Anda Yakin Ingin menghapust data "+ data.getValueAt(row, 1).toString(),"Hapus",
                JOptionPane.YES_NO_OPTION);
        if (result==0)
        {
       int d = TBdiary.getSelectedRow();
       DefaultTableModel dtmdel = (DefaultTableModel) TBdiary.getModel();
       dtmdel.removeRow(d);
       diaryku.remove(d);
       reset();
        }
        }
       
    }//GEN-LAST:event_BThapusActionPerformed

    private void BTtabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTtabelActionPerformed
        try{
//            object out merupakan inisialasi untuk mengolah file export
            BufferedWriter out = new BufferedWriter(new FileWriter("Export.txt"));
            //perulangan yang dimana menghitung c sebagai baris dan v sebagai column
            for(int c = 0; c < TBdiary.getRowCount(); c++){
                for(int v = 0; v < TBdiary.getColumnCount(); v++){
                    //lakukan penulisan berdasar nilai dari c dan v berdasarkan incrementnya
                  out.write(TBdiary.getValueAt(c, v).toString().replace("\n", "\\n")+"/"); 
                }
                //membuat penulisan di baris baru / enter
                out.newLine();
            }
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan dalam File");
            out.close();
        }catch(Exception e){
            System.err.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_BTtabelActionPerformed

    private void TFcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFcariActionPerformed
//method cari
    private void BTcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcariActionPerformed
        tampilDiary(TFcari.getText());
    }//GEN-LAST:event_BTcariActionPerformed
//method keluar
    private void BTexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTexitActionPerformed
        int result= JOptionPane.showConfirmDialog(null,"Apakah Yakin Mau Keluar","Exit",
                JOptionPane.YES_NO_OPTION);
        if (result==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_BTexitActionPerformed
//method import
    private void BTimporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTimporActionPerformed
        try{
            //membersihkan arraylist
           diaryku.clear();
           //milih file 
            BufferedReader masuk = new BufferedReader(new FileReader("Export.txt"));
            // scan file yang dimaksud
            Scanner data2 = new Scanner(masuk);
            //selama objek scan memilik baris lagi maka 
            while(data2.hasNextLine()){
                //ambil line selanjutnya selagi masih ada
                String row = data2.nextLine();
                // array data yang isinya dipisahka row yang dipisah dengan \
                String[] data = row.split("/");
                String tanggal = data[1];
                String subject = data[2];
                String isi = data[3].replace("\\n", "\n");
                
                diaryku.add(new Diary (Integer.parseInt(data[0]),tanggal,subject,isi));
            }
            JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception ex){
            System.err.println("Error"+ex.getMessage());
        }
    }//GEN-LAST:event_BTimporActionPerformed

    private void TFcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFcariKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFcariKeyTyped
//tombol reset
    private void BTresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTresetActionPerformed
        reset();
        tampilDiary("");
    }//GEN-LAST:event_BTresetActionPerformed
//checkobox
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        //jika checkbox diconteng maka jdatechooser1 diset tanggalhari ini dan dimantikan (tidak bisa diubah
        if(jCheckBox1.isSelected()){
            jDateChooser1.setDate(new Date());
            jDateChooser1.setEnabled(false);
        }else{
            //jika tidak diconteng jdatechooser1 hidup
            jDateChooser1.setEnabled(true);
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jScrollPane2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseReleased

    private void BTtabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTtabelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BTtabelMouseReleased
//method detail
    private void BTDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTDetailActionPerformed
        TableModel data = TBdiary.getModel();
        int row = TBdiary.getSelectedRow();
        //data baru sesuai dengan Diary yang diakses khusus untuk halaman detail
        diary = new Diary();
        // nilainya di set di bawah
        diary.setId(Integer.parseInt(data.getValueAt(row, 0).toString()));
        diary.setDate(data.getValueAt(row, 1).toString());
        diary.setSubject(data.getValueAt(row, 2).toString());
        diary.setIsi(data.getValueAt(row, 3).toString());
        //membuat object baru dari class Detail uI dengan parameter data baru diary
        DetailUI detailpage = new DetailUI(diary);
        //menampilkan detailUI form dari object detailpage
        detailpage.setVisible(true);
 
    }//GEN-LAST:event_BTDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTDetail;
    private javax.swing.JButton BTcari;
    private javax.swing.JButton BTedit;
    private javax.swing.JButton BTexit;
    private javax.swing.JButton BThapus;
    private javax.swing.JButton BTimpor;
    private javax.swing.JButton BTreset;
    private javax.swing.JButton BTsimpan;
    private javax.swing.JButton BTtabel;
    private javax.swing.JTextArea TAisi;
    private javax.swing.JTable TBdiary;
    private javax.swing.JTextField TFcari;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFsubject;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
 

}
